image: docker:27-dind

services:
  - docker:dind

stages:
  - prepare
  - test

build_image:
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest -t current:latest .
    - docker tag current:latest ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - Dockerfile
        - pyproject.toml
        - uv.lock

test:
  image: "${CI_REGISTRY_IMAGE}:latest"
  stage: test
  script:
    - molecule test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
