# tasks/_client_configuration.yml
---
- name: Initialize admin authorized keys
  set_fact:
    admin_authorized_keys: []

- name: Collect all customer keys for admin user
  set_fact:
    admin_authorized_keys: "{{ admin_authorized_keys + [{'key': item.key, 'state': 'present'}] }}"
  loop: "{{ mw_user_customer_users }}"

- name: Build admin user list
  set_fact:
    customer_admin_list:
      - "{{ mw_user_customer_template | combine({
              'name': mw_user_customer_admin_name,
              'authorized_keys': admin_authorized_keys
            })
          }}"

- name: Create shared admin user
  include_role:
    name: GROG.user
  vars:
    user_list: "{{ customer_admin_list }}"
    user_list_host: []
    user_list_group: []

- name: Set authorized keys for shared admin user
  include_role:
    name: GROG.authorized-key
  vars:
    authorized_key_list: "{{ customer_admin_list }}"
    authorized_key_list_host: []
    authorized_key_list_group: []

- name: Set sudo for shared admin user
  include_role:
    name: GROG.sudo
  vars:
    sudo_list: "{{ customer_admin_list }}"
    sudo_list_host: []
    sudo_list_group: []

- name: Configure individual client users
  block:
    - name: Initialize individual client user list
      set_fact:
        customer_user_list: []

    - name: Build individual client user list
      set_fact:
        customer_user_list: >-
          {{ customer_user_list + [
              mw_user_customer_template | combine({
                'name': item.name,
                'authorized_keys': [{'key': item.key, 'state': 'present'}]
              })
            ]
          }}
      loop: "{{ mw_user_customer_users }}"

    - name: Create individual client users
      include_role:
        name: GROG.user
      vars:
        user_list: "{{ customer_user_list }}"
        user_list_host: []
        user_list_group: []

    - name: Set authorized keys for individual client users
      include_role:
        name: GROG.authorized-key
      vars:
        authorized_key_list: "{{ customer_user_list }}"
        authorized_key_list_host: []
        authorized_key_list_group: []

    - name: Set sudo for individual client users
      include_role:
        name: GROG.sudo
      vars:
        sudo_list: "{{ customer_user_list }}"
        sudo_list_host: []
        sudo_list_group: []
  when: mw_user_customer_create_one_account_per_user | bool
