dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
    roles-path: "${MOLECULE_PROJECT_DIRECTORY}/molecule/client_accounts/roles"
driver:
  name: docker
platforms:
  - name: client-admin-only
    image: ubuntu:20.04
    groups:
      - admin_only
    pre_build_image: false
    dockerfile: Dockerfile.j2
  - name: client-multiple-users
    image: ubuntu:20.04
    groups:
      - multiple_users
    pre_build_image: false
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    group_vars:
      admin_only:
        mw_user_customer_create_one_account_per_user: false
        mw_user_customer_users:
          - name: user1
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIErQer6XoCjc9d2JN46jjtAZHsDiz7FDWVwstI8a8THx user1"
          - name: user2
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXxlhX8Vm2fM67RA2R7fiZPGvTCuoy/DOtoW1wVBcko user2"
      multiple_users:
        mw_user_customer_create_one_account_per_user: true
        mw_user_customer_users:
          - name: user1
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIErQer6XoCjc9d2JN46jjtAZHsDiz7FDWVwstI8a8THx user1"
          - name: user2
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXxlhX8Vm2fM67RA2R7fiZPGvTCuoy/DOtoW1wVBcko user2"
          - name: user3
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnvRgNEQNqcuFWD4YKsqGNEW7wUuU98a3KcM699n8eJ user3"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
