---
- name: Verify Client Accounts
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if admin user exists
      command: "id admin"
      changed_when: false

    - name: Verify individual client users are created
      command: "id {{ item.name }}"
      changed_when: false
      when: inventory_hostname in groups['multiple_users']
      loop: "{{ mw_user_customer_users }}"
